language: haskell
ghc: 7.6
install:
  - echo "yes" | sudo apt-add-repository ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq clang-3.3
  - sudo apt-get install -qq boost1.55
  - wget http://download.nanomsg.org/nanomsg-0.3-beta.tar.gz
  - tar -xvzf nanomsg-0.3-beta.tar.gz
  - mkdir -p ~/software/nanomsg
  - ./nanomsg-0.3-beta/configure --prefix ~/software/nanomsg && make && make install  
  - wget http://www.partow.net/downloads/strtk.zip
  - mv strtk.zip ~/software/ && cd ~/software && unzip strtk.zip && ls && cd -
  - cd ~/software && git clone git://gitorious.org/json-spirit/json-spirit.git && cd -
  - cabal install cabal-install && cabal --version
  - export PATH=~/.cabal/bin:$PATH
  - mkdir ../K3-Driver
  - cd ../K3-Driver
  - git clone https://github.com/DaMSL/K3-Driver.git .
  - cabal sandbox init
  - cabal sandbox add-source ../K3-Core
  - sudo pip install six
script:
  - ls ~/software/nanomsg/include
  - cd ../K3-Driver
  - cabal install --only-dependencies --disable-documentation
  - cabal configure
  - cabal build
  - scripts/tests/tests.py -l scripts/tests/passed_tests.txt
  - ./dist/build/k3/k3 -I ../K3-Core/lib/k3 compile -l cpp --clang --runtime '../K3-Core/runtime' --cpp-flags='-DBOOST_LOG_DYN_LINK -I../K3-Core/runtime/cpp -lboost_serialization -lboost_system -lboost_regex -lboost_thread -lpthread -lboost_log_setup -lboost_log -lboost_program_options -I/home/travis/software/nanomsg/include -I/home/travis/software/strtk -I/home/travis/software/json-spirit/json_spirit/' ../K3-Core/examples/fibonacci.k3
