language: haskell
ghc: 7.6
script:
  - mkdir ../K3-Driver
  - cd ../K3-Driver
  - git clone https://github.com/DaMSL/K3-Driver.git .
  - cabal sandbox init
  - cabal sandbox add-source ../K3-Core
  - cabal install --only-dependencies --disable-documentation
  - cabal configure
  - cabal build
