language: haskell
ghc: 7.6
install:
  - echo "yes" | sudo apt-add-repository ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq clang-3.3
  - sudo apt-get install -qq boost1.55
  - wget http://download.nanomsg.org/nanomsg-0.3-beta.tar.gz
  - tar -xvzf nanomsg-0.3-beta.tar.gz
  - mkdir -p ~/software/nanomsg
  - ./nanomsg-0.3-beta/configure --prefix ~/software/nanomsg && make && make install  
  - cabal install cabal-install && cabal --version
  - export PATH=~/.cabal/bin:$PATH
  - mkdir ../K3-Driver
  - cd ../K3-Driver
  - git clone https://github.com/DaMSL/K3-Driver.git .
  - cabal sandbox init
  - cabal sandbox add-source ../K3-Core
  - sudo pip install six
script:
  - ls ~/software/nanomsg/include
  - cd ../K3-Driver
  - cabal install --only-dependencies --disable-documentation
  - cabal configure
  - cabal build
    #- scripts/tests/tests.py -l scripts/tests/passed_tests.txt
  - ./compile.sh ../K3-Core/examples/fibonacci.k3
  - ./compile.sh ../K3-Core/examples/distributed/amplab/q1.k3
    #- ./compile.sh ../K3-Core/examples/distributed/amplab/q2.k3
