- hosts: target_hosts
  tasks:
    - include: plays/deploy_k3.yml
      vars:
        app_name: pagerank
        binary: /tmp/pagerank
        numprocs: 16
        k3_variables:
          damping_factor: 0.15
          iterations: 2
          master: "<192.168.0.40:40000>" # TODO, just set to first peer?
          role: '"s1"'
        data_files:
          - name: "dataFiles"
            num: 128
            prefix: "/local/data/parts/adj.txt"
