---
volumes:
  - {host: /local, container: /local}
name: role 1
peers: 128
hostmask: ".*hm.*"
k3_globals:
  role: [{i: rows}]
  #role: rows
  master: auto
  thresh: 1000
  slice_length: 8
k3_data:
  - {var: rankingsFiles, path: /local/data/amplab/1024/rankings, policy: global}
  - {var: uservisitsFiles, path: /local/data/amplab/1024/uservisits, policy: global}
envars:
  - {name: LD_PRELOAD, value: /usr/lib/libjemalloc.so}
  - {name: MALLOC_CONF, value: "prof:true,prof_final:true,prof_accum:true,prof_prefix:K3,prof_active:false"}