volumes:
  - {host: /data, container: /data}
name: role 1
peers: 128
hostmask: ".*hm.*"
k3_globals:
  role: s1
  master: auto
  iterations: 10
k3_data:
  - {var: dataFiles, path: /data/graph/twitter, policy: global}