volumes:
  - {host: /local, container: /local}
name: role 1
peers: 128
hostmask: ".*hm.*"
k3_globals:
  role: [{i: rows}]
  master: auto
k3_data:
  - {var: dataFiles, path: /local/data/tpch100g/lineitem, policy: global}
  - {var: lineitemFiles, path: /local/data/tpch100g/lineitem, policy: global}
  - {var: customerFiles, path: /local/data/tpch100g/customer, policy: global}  
  - {var: ordersFiles, path: /local/data/tpch100g/orders, policy: global}  
  - {var: supplierFiles, path: /local/data/tpch100g/supplier, policy: global}  
  - {var: partsuppFiles, path: /local/data/tpch100g/partsupp, policy: global}  
  - {var: partFiles, path: /local/data/tpch100g/part, policy: global}  
  - {var: regionFiles, path: /local/data/tpch100g/region, policy: replicate}
  - {var: nationFiles, path: /local/data/tpch100g/nation, policy: replicate}
envars:
  - {name: LD_PRELOAD, value: /usr/lib/libjemalloc.so}
  - {name: MALLOC_CONF, value: "prof:true,prof_final:true,prof_accum:false,prof_prefix:K3,prof_active:false"}