<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>k3</string>
	</array>
	<key>name</key>
	<string>K3</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#declarations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#memdecls</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#annotations</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(as|bind|case|content|effects|else|forall|fresh|fun|given|horizon|if|in|io|include|let|of|return|self|shared|structure|then|type|with)\b</string>
			<key>name</key>
			<string>keyword.control.k3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(address|bool|byte|collection|decl|expr|ind|int|label|labeltype|literal|option|real|string)\b</string>
			<key>name</key>
			<string>storage.type.k3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(immut|mut)\b</string>
			<key>name</key>
			<string>storage.modifier.k3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|empty|Some|None)\b</string>
			<key>name</key>
			<string>constant.language.k3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(\)</string>
			<key>name</key>
			<string>constant.language.unit.k3</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Floats are always decimal</string>
			<key>match</key>
			<string>\b([0-9]+\.[0-9]+([eE][+-]?[0-9]+)?|[0-9]+[eE][+-]?[0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.float.k3</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9]+|0([xX][0-9a-fA-F]+|[oO][0-7]+))\b</string>
			<key>name</key>
			<string>constant.numeric.k3</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.k3</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$|"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.k3</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.haskell</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>annotations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(@:)\s*(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language.k3</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.k3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*([^\}]+)\s*(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.k3</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.k3</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.propusage.k3</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language.k3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*([a-zA-Z0-9_']+)\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.k3</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.propusage.k3</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)\s*(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language.k3</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.k3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*([^\}]+)\s*(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.k3</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.k3</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.annusage.k3</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(@)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language.k3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*([a-zA-Z0-9_']+)\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.k3</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.annusage.k3</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.k3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.k3</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.k3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.k3</string>
				</dict>
			</array>
		</dict>
		<key>declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(trigger|declare|source|sink)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.k3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*([a-zA-Z0-9_']+)\s*(:)\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.k3</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.colon.k3</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.k3</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(annotation|control)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.k3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*([a-zA-Z0-9_']+)\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.k3</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.annotation.k3</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(typedef)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.k3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*([a-zA-Z0-9_']+)\s*(=)\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.k3</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.equals.k3</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.typedef.k3</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(feed)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.k3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*([a-zA-Z0-9_']+)\s*(\|&gt;)\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.k3</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.pipe.k3</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.feed.k3</string>
				</dict>
			</array>
		</dict>
		<key>memdecls</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(provides|requires)\b\s*\b(lifted?)\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.k3</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.k3</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\s*([a-zA-Z0-9_']+)\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.k3</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.declaration.member.k3</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.syntax_name</string>
	<key>uuid</key>
	<string>57951741-2557-458e-8e7a-e16402697106</string>
</dict>
</plist>
