  # Define Constants
  - name: Define constants
    set_fact:
      peers: "[ {%- for key in play_hosts -%} {% for i in range(numprocs) %} {addr: <{{ hostvars[key].ip }}:{{40000 + i}}> }{%- if not loop.last %},{% endif %} {%- endfor %} {%- if not loop.last %},{% endif %}{%- endfor %}]"
      setup_dir: /local/deploy/k3_{{app_name}}/setup/
      data_dir: /local/deploy/k3_{{app_name}}/data/
      docker_image: k3_{{app_name}}
      results_dir: /tmp/k3_results/k3_{{app_name}} # Local side. 
      colon: ":"
      num_hosts: "{{play_hosts | count}}"
      num_peers: "{{(play_hosts | count) * numprocs}}"

  # copy over files
  - name: setup directories on the remote host
    shell: mkdir -p {{setup_dir}} {{data_dir}}{{item}}
    with_sequence: start=40000 end={{40000+numprocs-1 }}

  - name: copy the binary to the remote host
    copy: src={{binary}} dest={{setup_dir}}k3
  
  - name: copy the Dockerfile to the remote host
    copy: src=files/Dockerfile dest={{setup_dir}}
  
  - name: copy the run script to the remote host
    copy: src=files/run_k3.sh dest={{setup_dir}}
  

  # docker cleanup
  - name: kill existing docker containers for this app
    docker: name="{{docker_image}}_{{item}}" image={{docker_image}} state=killed
    ignore_errors: yes
    with_sequence: start=40000 end={{40000+numprocs-1}}

  - name: remove existing docker containers for this app
    shell: docker rm -f {{docker_image}}_{{item}} 
    ignore_errors: yes
    with_sequence: start=40000 end={{40000+numprocs-1}}

  - name: delete existing docker image for this app
    docker_image: name={{docker_image}} state=absent
    ignore_errors: yes

  # docker build
  - name: build the docker image for this app
    shell: docker build --no-cache=true -t {{docker_image}} {{setup_dir}}
