// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mesos/authentication/authentication.proto

#ifndef PROTOBUF_mesos_2fauthentication_2fauthentication_2eproto__INCLUDED
#define PROTOBUF_mesos_2fauthentication_2fauthentication_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "mesos/mesos.pb.h"
// @@protoc_insertion_point(includes)

namespace mesos {
namespace internal {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_mesos_2fauthentication_2fauthentication_2eproto();
void protobuf_AssignDesc_mesos_2fauthentication_2fauthentication_2eproto();
void protobuf_ShutdownFile_mesos_2fauthentication_2fauthentication_2eproto();

class AuthenticateMessage;
class AuthenticationMechanismsMessage;
class AuthenticationStartMessage;
class AuthenticationStepMessage;
class AuthenticationCompletedMessage;
class AuthenticationFailedMessage;
class AuthenticationErrorMessage;

// ===================================================================

class AuthenticateMessage : public ::google::protobuf::Message {
 public:
  AuthenticateMessage();
  virtual ~AuthenticateMessage();

  AuthenticateMessage(const AuthenticateMessage& from);

  inline AuthenticateMessage& operator=(const AuthenticateMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthenticateMessage& default_instance();

  void Swap(AuthenticateMessage* other);

  // implements Message ----------------------------------------------

  AuthenticateMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AuthenticateMessage& from);
  void MergeFrom(const AuthenticateMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string pid = 1;
  inline bool has_pid() const;
  inline void clear_pid();
  static const int kPidFieldNumber = 1;
  inline const ::std::string& pid() const;
  inline void set_pid(const ::std::string& value);
  inline void set_pid(const char* value);
  inline void set_pid(const char* value, size_t size);
  inline ::std::string* mutable_pid();
  inline ::std::string* release_pid();
  inline void set_allocated_pid(::std::string* pid);

  // @@protoc_insertion_point(class_scope:mesos.internal.AuthenticateMessage)
 private:
  inline void set_has_pid();
  inline void clear_has_pid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* pid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_mesos_2fauthentication_2fauthentication_2eproto();
  friend void protobuf_AssignDesc_mesos_2fauthentication_2fauthentication_2eproto();
  friend void protobuf_ShutdownFile_mesos_2fauthentication_2fauthentication_2eproto();

  void InitAsDefaultInstance();
  static AuthenticateMessage* default_instance_;
};
// -------------------------------------------------------------------

class AuthenticationMechanismsMessage : public ::google::protobuf::Message {
 public:
  AuthenticationMechanismsMessage();
  virtual ~AuthenticationMechanismsMessage();

  AuthenticationMechanismsMessage(const AuthenticationMechanismsMessage& from);

  inline AuthenticationMechanismsMessage& operator=(const AuthenticationMechanismsMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthenticationMechanismsMessage& default_instance();

  void Swap(AuthenticationMechanismsMessage* other);

  // implements Message ----------------------------------------------

  AuthenticationMechanismsMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AuthenticationMechanismsMessage& from);
  void MergeFrom(const AuthenticationMechanismsMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string mechanisms = 1;
  inline int mechanisms_size() const;
  inline void clear_mechanisms();
  static const int kMechanismsFieldNumber = 1;
  inline const ::std::string& mechanisms(int index) const;
  inline ::std::string* mutable_mechanisms(int index);
  inline void set_mechanisms(int index, const ::std::string& value);
  inline void set_mechanisms(int index, const char* value);
  inline void set_mechanisms(int index, const char* value, size_t size);
  inline ::std::string* add_mechanisms();
  inline void add_mechanisms(const ::std::string& value);
  inline void add_mechanisms(const char* value);
  inline void add_mechanisms(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& mechanisms() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_mechanisms();

  // @@protoc_insertion_point(class_scope:mesos.internal.AuthenticationMechanismsMessage)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::std::string> mechanisms_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_mesos_2fauthentication_2fauthentication_2eproto();
  friend void protobuf_AssignDesc_mesos_2fauthentication_2fauthentication_2eproto();
  friend void protobuf_ShutdownFile_mesos_2fauthentication_2fauthentication_2eproto();

  void InitAsDefaultInstance();
  static AuthenticationMechanismsMessage* default_instance_;
};
// -------------------------------------------------------------------

class AuthenticationStartMessage : public ::google::protobuf::Message {
 public:
  AuthenticationStartMessage();
  virtual ~AuthenticationStartMessage();

  AuthenticationStartMessage(const AuthenticationStartMessage& from);

  inline AuthenticationStartMessage& operator=(const AuthenticationStartMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthenticationStartMessage& default_instance();

  void Swap(AuthenticationStartMessage* other);

  // implements Message ----------------------------------------------

  AuthenticationStartMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AuthenticationStartMessage& from);
  void MergeFrom(const AuthenticationStartMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string mechanism = 1;
  inline bool has_mechanism() const;
  inline void clear_mechanism();
  static const int kMechanismFieldNumber = 1;
  inline const ::std::string& mechanism() const;
  inline void set_mechanism(const ::std::string& value);
  inline void set_mechanism(const char* value);
  inline void set_mechanism(const char* value, size_t size);
  inline ::std::string* mutable_mechanism();
  inline ::std::string* release_mechanism();
  inline void set_allocated_mechanism(::std::string* mechanism);

  // optional bytes data = 2;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 2;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:mesos.internal.AuthenticationStartMessage)
 private:
  inline void set_has_mechanism();
  inline void clear_has_mechanism();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* mechanism_;
  ::std::string* data_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_mesos_2fauthentication_2fauthentication_2eproto();
  friend void protobuf_AssignDesc_mesos_2fauthentication_2fauthentication_2eproto();
  friend void protobuf_ShutdownFile_mesos_2fauthentication_2fauthentication_2eproto();

  void InitAsDefaultInstance();
  static AuthenticationStartMessage* default_instance_;
};
// -------------------------------------------------------------------

class AuthenticationStepMessage : public ::google::protobuf::Message {
 public:
  AuthenticationStepMessage();
  virtual ~AuthenticationStepMessage();

  AuthenticationStepMessage(const AuthenticationStepMessage& from);

  inline AuthenticationStepMessage& operator=(const AuthenticationStepMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthenticationStepMessage& default_instance();

  void Swap(AuthenticationStepMessage* other);

  // implements Message ----------------------------------------------

  AuthenticationStepMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AuthenticationStepMessage& from);
  void MergeFrom(const AuthenticationStepMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes data = 1;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 1;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:mesos.internal.AuthenticationStepMessage)
 private:
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* data_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_mesos_2fauthentication_2fauthentication_2eproto();
  friend void protobuf_AssignDesc_mesos_2fauthentication_2fauthentication_2eproto();
  friend void protobuf_ShutdownFile_mesos_2fauthentication_2fauthentication_2eproto();

  void InitAsDefaultInstance();
  static AuthenticationStepMessage* default_instance_;
};
// -------------------------------------------------------------------

class AuthenticationCompletedMessage : public ::google::protobuf::Message {
 public:
  AuthenticationCompletedMessage();
  virtual ~AuthenticationCompletedMessage();

  AuthenticationCompletedMessage(const AuthenticationCompletedMessage& from);

  inline AuthenticationCompletedMessage& operator=(const AuthenticationCompletedMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthenticationCompletedMessage& default_instance();

  void Swap(AuthenticationCompletedMessage* other);

  // implements Message ----------------------------------------------

  AuthenticationCompletedMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AuthenticationCompletedMessage& from);
  void MergeFrom(const AuthenticationCompletedMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:mesos.internal.AuthenticationCompletedMessage)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_mesos_2fauthentication_2fauthentication_2eproto();
  friend void protobuf_AssignDesc_mesos_2fauthentication_2fauthentication_2eproto();
  friend void protobuf_ShutdownFile_mesos_2fauthentication_2fauthentication_2eproto();

  void InitAsDefaultInstance();
  static AuthenticationCompletedMessage* default_instance_;
};
// -------------------------------------------------------------------

class AuthenticationFailedMessage : public ::google::protobuf::Message {
 public:
  AuthenticationFailedMessage();
  virtual ~AuthenticationFailedMessage();

  AuthenticationFailedMessage(const AuthenticationFailedMessage& from);

  inline AuthenticationFailedMessage& operator=(const AuthenticationFailedMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthenticationFailedMessage& default_instance();

  void Swap(AuthenticationFailedMessage* other);

  // implements Message ----------------------------------------------

  AuthenticationFailedMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AuthenticationFailedMessage& from);
  void MergeFrom(const AuthenticationFailedMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:mesos.internal.AuthenticationFailedMessage)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_mesos_2fauthentication_2fauthentication_2eproto();
  friend void protobuf_AssignDesc_mesos_2fauthentication_2fauthentication_2eproto();
  friend void protobuf_ShutdownFile_mesos_2fauthentication_2fauthentication_2eproto();

  void InitAsDefaultInstance();
  static AuthenticationFailedMessage* default_instance_;
};
// -------------------------------------------------------------------

class AuthenticationErrorMessage : public ::google::protobuf::Message {
 public:
  AuthenticationErrorMessage();
  virtual ~AuthenticationErrorMessage();

  AuthenticationErrorMessage(const AuthenticationErrorMessage& from);

  inline AuthenticationErrorMessage& operator=(const AuthenticationErrorMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AuthenticationErrorMessage& default_instance();

  void Swap(AuthenticationErrorMessage* other);

  // implements Message ----------------------------------------------

  AuthenticationErrorMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AuthenticationErrorMessage& from);
  void MergeFrom(const AuthenticationErrorMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string error = 1;
  inline bool has_error() const;
  inline void clear_error();
  static const int kErrorFieldNumber = 1;
  inline const ::std::string& error() const;
  inline void set_error(const ::std::string& value);
  inline void set_error(const char* value);
  inline void set_error(const char* value, size_t size);
  inline ::std::string* mutable_error();
  inline ::std::string* release_error();
  inline void set_allocated_error(::std::string* error);

  // @@protoc_insertion_point(class_scope:mesos.internal.AuthenticationErrorMessage)
 private:
  inline void set_has_error();
  inline void clear_has_error();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* error_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_mesos_2fauthentication_2fauthentication_2eproto();
  friend void protobuf_AssignDesc_mesos_2fauthentication_2fauthentication_2eproto();
  friend void protobuf_ShutdownFile_mesos_2fauthentication_2fauthentication_2eproto();

  void InitAsDefaultInstance();
  static AuthenticationErrorMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// AuthenticateMessage

// required string pid = 1;
inline bool AuthenticateMessage::has_pid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AuthenticateMessage::set_has_pid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AuthenticateMessage::clear_has_pid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AuthenticateMessage::clear_pid() {
  if (pid_ != &::google::protobuf::internal::kEmptyString) {
    pid_->clear();
  }
  clear_has_pid();
}
inline const ::std::string& AuthenticateMessage::pid() const {
  return *pid_;
}
inline void AuthenticateMessage::set_pid(const ::std::string& value) {
  set_has_pid();
  if (pid_ == &::google::protobuf::internal::kEmptyString) {
    pid_ = new ::std::string;
  }
  pid_->assign(value);
}
inline void AuthenticateMessage::set_pid(const char* value) {
  set_has_pid();
  if (pid_ == &::google::protobuf::internal::kEmptyString) {
    pid_ = new ::std::string;
  }
  pid_->assign(value);
}
inline void AuthenticateMessage::set_pid(const char* value, size_t size) {
  set_has_pid();
  if (pid_ == &::google::protobuf::internal::kEmptyString) {
    pid_ = new ::std::string;
  }
  pid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AuthenticateMessage::mutable_pid() {
  set_has_pid();
  if (pid_ == &::google::protobuf::internal::kEmptyString) {
    pid_ = new ::std::string;
  }
  return pid_;
}
inline ::std::string* AuthenticateMessage::release_pid() {
  clear_has_pid();
  if (pid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = pid_;
    pid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void AuthenticateMessage::set_allocated_pid(::std::string* pid) {
  if (pid_ != &::google::protobuf::internal::kEmptyString) {
    delete pid_;
  }
  if (pid) {
    set_has_pid();
    pid_ = pid;
  } else {
    clear_has_pid();
    pid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// AuthenticationMechanismsMessage

// repeated string mechanisms = 1;
inline int AuthenticationMechanismsMessage::mechanisms_size() const {
  return mechanisms_.size();
}
inline void AuthenticationMechanismsMessage::clear_mechanisms() {
  mechanisms_.Clear();
}
inline const ::std::string& AuthenticationMechanismsMessage::mechanisms(int index) const {
  return mechanisms_.Get(index);
}
inline ::std::string* AuthenticationMechanismsMessage::mutable_mechanisms(int index) {
  return mechanisms_.Mutable(index);
}
inline void AuthenticationMechanismsMessage::set_mechanisms(int index, const ::std::string& value) {
  mechanisms_.Mutable(index)->assign(value);
}
inline void AuthenticationMechanismsMessage::set_mechanisms(int index, const char* value) {
  mechanisms_.Mutable(index)->assign(value);
}
inline void AuthenticationMechanismsMessage::set_mechanisms(int index, const char* value, size_t size) {
  mechanisms_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AuthenticationMechanismsMessage::add_mechanisms() {
  return mechanisms_.Add();
}
inline void AuthenticationMechanismsMessage::add_mechanisms(const ::std::string& value) {
  mechanisms_.Add()->assign(value);
}
inline void AuthenticationMechanismsMessage::add_mechanisms(const char* value) {
  mechanisms_.Add()->assign(value);
}
inline void AuthenticationMechanismsMessage::add_mechanisms(const char* value, size_t size) {
  mechanisms_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
AuthenticationMechanismsMessage::mechanisms() const {
  return mechanisms_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
AuthenticationMechanismsMessage::mutable_mechanisms() {
  return &mechanisms_;
}

// -------------------------------------------------------------------

// AuthenticationStartMessage

// required string mechanism = 1;
inline bool AuthenticationStartMessage::has_mechanism() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AuthenticationStartMessage::set_has_mechanism() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AuthenticationStartMessage::clear_has_mechanism() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AuthenticationStartMessage::clear_mechanism() {
  if (mechanism_ != &::google::protobuf::internal::kEmptyString) {
    mechanism_->clear();
  }
  clear_has_mechanism();
}
inline const ::std::string& AuthenticationStartMessage::mechanism() const {
  return *mechanism_;
}
inline void AuthenticationStartMessage::set_mechanism(const ::std::string& value) {
  set_has_mechanism();
  if (mechanism_ == &::google::protobuf::internal::kEmptyString) {
    mechanism_ = new ::std::string;
  }
  mechanism_->assign(value);
}
inline void AuthenticationStartMessage::set_mechanism(const char* value) {
  set_has_mechanism();
  if (mechanism_ == &::google::protobuf::internal::kEmptyString) {
    mechanism_ = new ::std::string;
  }
  mechanism_->assign(value);
}
inline void AuthenticationStartMessage::set_mechanism(const char* value, size_t size) {
  set_has_mechanism();
  if (mechanism_ == &::google::protobuf::internal::kEmptyString) {
    mechanism_ = new ::std::string;
  }
  mechanism_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AuthenticationStartMessage::mutable_mechanism() {
  set_has_mechanism();
  if (mechanism_ == &::google::protobuf::internal::kEmptyString) {
    mechanism_ = new ::std::string;
  }
  return mechanism_;
}
inline ::std::string* AuthenticationStartMessage::release_mechanism() {
  clear_has_mechanism();
  if (mechanism_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = mechanism_;
    mechanism_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void AuthenticationStartMessage::set_allocated_mechanism(::std::string* mechanism) {
  if (mechanism_ != &::google::protobuf::internal::kEmptyString) {
    delete mechanism_;
  }
  if (mechanism) {
    set_has_mechanism();
    mechanism_ = mechanism;
  } else {
    clear_has_mechanism();
    mechanism_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bytes data = 2;
inline bool AuthenticationStartMessage::has_data() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AuthenticationStartMessage::set_has_data() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AuthenticationStartMessage::clear_has_data() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AuthenticationStartMessage::clear_data() {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& AuthenticationStartMessage::data() const {
  return *data_;
}
inline void AuthenticationStartMessage::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void AuthenticationStartMessage::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void AuthenticationStartMessage::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AuthenticationStartMessage::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  return data_;
}
inline ::std::string* AuthenticationStartMessage::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void AuthenticationStartMessage::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// AuthenticationStepMessage

// required bytes data = 1;
inline bool AuthenticationStepMessage::has_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AuthenticationStepMessage::set_has_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AuthenticationStepMessage::clear_has_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AuthenticationStepMessage::clear_data() {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& AuthenticationStepMessage::data() const {
  return *data_;
}
inline void AuthenticationStepMessage::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void AuthenticationStepMessage::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void AuthenticationStepMessage::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AuthenticationStepMessage::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  return data_;
}
inline ::std::string* AuthenticationStepMessage::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void AuthenticationStepMessage::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// AuthenticationCompletedMessage

// -------------------------------------------------------------------

// AuthenticationFailedMessage

// -------------------------------------------------------------------

// AuthenticationErrorMessage

// optional string error = 1;
inline bool AuthenticationErrorMessage::has_error() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AuthenticationErrorMessage::set_has_error() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AuthenticationErrorMessage::clear_has_error() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AuthenticationErrorMessage::clear_error() {
  if (error_ != &::google::protobuf::internal::kEmptyString) {
    error_->clear();
  }
  clear_has_error();
}
inline const ::std::string& AuthenticationErrorMessage::error() const {
  return *error_;
}
inline void AuthenticationErrorMessage::set_error(const ::std::string& value) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::kEmptyString) {
    error_ = new ::std::string;
  }
  error_->assign(value);
}
inline void AuthenticationErrorMessage::set_error(const char* value) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::kEmptyString) {
    error_ = new ::std::string;
  }
  error_->assign(value);
}
inline void AuthenticationErrorMessage::set_error(const char* value, size_t size) {
  set_has_error();
  if (error_ == &::google::protobuf::internal::kEmptyString) {
    error_ = new ::std::string;
  }
  error_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AuthenticationErrorMessage::mutable_error() {
  set_has_error();
  if (error_ == &::google::protobuf::internal::kEmptyString) {
    error_ = new ::std::string;
  }
  return error_;
}
inline ::std::string* AuthenticationErrorMessage::release_error() {
  clear_has_error();
  if (error_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = error_;
    error_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void AuthenticationErrorMessage::set_allocated_error(::std::string* error) {
  if (error_ != &::google::protobuf::internal::kEmptyString) {
    delete error_;
  }
  if (error) {
    set_has_error();
    error_ = error;
  } else {
    clear_has_error();
    error_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace internal
}  // namespace mesos

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mesos_2fauthentication_2fauthentication_2eproto__INCLUDED
