---
- hosts: '{{ hosts }}'
  sudo: yes

  vars_files:
   - "config.yml"

  tasks:
   - name: Install pip
     shell: easy_install pip

   - name: Install docker-py
     pip: name=docker-py version=1.1.0 state=present
