---
- hosts: '{{ hosts }}'
  sudo: yes

  vars_files:
   - "config.yml"
  vars:
    masterip: '{{ hostvars[groups[hosts][masteridx]].ansible_default_ipv4.address }}'

  tasks:
   - name: Kill compiler service
     shell: docker exec -ti {{ cname }} /usr/bin/killall k3
     register: client

   - debug: var=client.stdout_lines

