---
- hosts: '{{ master }}'
  vars_files:
   - "config.yml"

- hosts: '{{ client }}'
  sudo: yes

  vars_files:
   - "config.yml"

  vars:
    masterip: '{{ hostvars[groups[hosts][masteridx]].ansible_default_ipv4.address }}'

  tasks:
   - name: Submit compile job
     shell: docker exec -ti {{ cname }} /k3/K3/tools/scripts/run/service.sh submit --svid client-{{ ansible_hostname }} --host {{ masterip }} --port {{ port }} {{ compileargs }} +RTS -N -RTS 
     register: client

   - debug: var=client.stdout_lines

