data_files:
  - variable_name: "rankings_file"
    path_prefix: "/local_data/sf5/128/rankings_sf5_128l/rankings_sf5_128l_"
    path_suffix_fmt: "%03d"

k3_bindings:
  x: 1000
  role: '"s1"'
  master: "<192.168.0.40>"

hosts:
  - name: qp-hm1
    ip: "192.168.0.40"
    num_peers: 16
    file_start_index: 0

  - name: qp-hm2
    ip: "192.168.0.41"
    num_peers: 16
    file_start_index: 16

  - name: qp-hm3
    ip: "192.168.0.42"
    num_peers: 16
    file_start_index: 32

  - name: qp-hm5
    ip: "192.168.0.44"
    num_peers: 16
    file_start_index: 64
