ip: 192.168.0.42
local_peers:
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_032"'}
  port: 40000
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_033"'}
  port: 40001
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_034"'}
  port: 40002
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_035"'}
  port: 40003
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_036"'}
  port: 40004
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_037"'}
  port: 40005
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_038"'}
  port: 40006
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_039"'}
  port: 40007
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_040"'}
  port: 40008
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_041"'}
  port: 40009
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_042"'}
  port: 40010
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_043"'}
  port: 40011
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_044"'}
  port: 40012
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_045"'}
  port: 40013
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_046"'}
  port: 40014
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_047"'}
  port: 40015
