ip: 192.168.0.44
local_peers:
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_064"'}
  port: 40000
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_065"'}
  port: 40001
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_066"'}
  port: 40002
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_067"'}
  port: 40003
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_068"'}
  port: 40004
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_069"'}
  port: 40005
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_070"'}
  port: 40006
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_071"'}
  port: 40007
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_072"'}
  port: 40008
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_073"'}
  port: 40009
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_074"'}
  port: 40010
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_075"'}
  port: 40011
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_076"'}
  port: 40012
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_077"'}
  port: 40013
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_078"'}
  port: 40014
- overrides: {rankings_file: '"/local_data/sf5/128l/rankings_sf5_128l/rankings_sf5_128l_079"'}
  port: 40015
