---
name: role 1
volumes:
  - {host: /local, container: /local}
peers: 128
peers_per_host: 16
hostmask: ".*qp-hm.*"
k3_globals:
  role: rows
  master: auto
k3_data:
  - {var: lineitemFiles, path: /local/data/tpch100g/lineitem, policy: global}
  - {var: ordersFiles, path: /local/data/tpch100g/orders, policy: global}
  - {var: customerFiles, path: /local/data/tpch100g/customer, policy: global}
  - {var: supplierFiles, path: /local/data/tpch100g/supplier, policy: global}
  - {var: nationFiles, path: /local/data/tpch100g/nation, policy: replicate}
  - {var: regionFiles, path: /local/data/tpch100g/region, policy: replicate}
