---
name: role 1
volumes:
  - {host: /data, container: /data}
peers: 16
peers_per_host: 1
hostmask: ".*qp-h.*"
k3_globals:
  role: rows
  master: auto
k3_data:
  - {var: lineitemFiles, path: /data/scalability/16/tables/lineitem, policy: global}
  - {var: ordersFiles, path: /data/scalability/16/tables/orders, policy: global}
  - {var: customerFiles, path: /data/scalability/16/tables/customer, policy: global}
  - {var: supplierFiles, path: /data/scalability/16/tables/supplier, policy: global}
  - {var: nationFiles, path: /data/scalability/16/tables/nation, policy: replicate}
  - {var: regionFiles, path: /data/scalability/16/tables/region, policy: replicate}
  - {var: lineitemLineCountFiles, path: /data/scalability/16/linecounts/lineitem, policy: global}
  - {var: ordersLineCountFiles, path: /data/scalability/16/linecounts/orders, policy: global}
  - {var: customerLineCountFiles, path: /data/scalability/16/linecounts/customer, policy: global}
  - {var: supplierLineCountFiles, path: /data/scalability/16/linecounts/supplier, policy: global}
