---
volumes:
  - {host: /data, container: /data}
name: role 1
peers: 128
peers_per_host: 1
hostmask: ".*qp-hd.*"
k3_globals:
  role: rows
  master: auto
  profilingEnabled: True
k3_data:
  - {var: dataLineCountFiles, path: /data/scalability/64/linecounts/lineitem, policy: global}
  - {var: dataFiles, path: /data/scalability/64/tables/lineitem, policy: global}
