---
name: role 1
volumes:
  - {host: /local, container: /local}
peers: 112
peers_per_host: 16
hostmask: ".*qp-hm.*"
k3_globals:
  role: rows
  master: auto
k3_data:
  - {var: dataFiles, path: /local/data/tpch10g/lineitem, policy: global}
