---
name: role 1
volumes:
  - {host: /data, container: /data}
peers: 16
peers_per_host: 1
hostmask: ".*qp-h.*"
k3_globals:
  role: rows
  master: auto
k3_data:
  - {var: dataLineCountFiles, path: /data/scalability/16/linecounts/lineitem, policy: global}
  - {var: dataFiles, path: /data/scalability/16/tables/lineitem, policy: global}
