---
name: role 1
peers: 128
hostmask: ".*hd.*"
k3_globals:
  role: rows
  master: auto
  profilingEnabled: True
k3_data:
  - {var: lineitemFiles, path: /data/scalability/128/lineitem, policy: global}
  - {var: ordersFiles, path: /data/scalability/128/orders, policy: global}
  - {var: customerFiles, path: /data/scalability/128/customer, policy: global}
