---
name: role 1
peers: 60
max_peers_per_host: 4
hostmask: ".*qp-h.*"
k3_globals:
  role: rows
  master: auto
  profilingEnabled: True
k3_data:
  - {var: dataLineCountFiles, path: /data/scalability/64/linecounts/lineitem, policy: global}
  - {var: dataFiles, path: /data/scalability/64/tables/lineitem, policy: global}
