---
name: role 1
peers: 128
hostmask: ".*hd.*"
k3_globals:
  role: rows
  master: auto
  profilingEnabled: True
k3_data:
  - {var: dataLineCountFiles, path: /data/scalability/128/linecounts/lineitem, policy: global}
  - {var: dataFiles, path: /data/scalability/128/tables/lineitem, policy: global}
