---
name: role 1
volumes:
  - {host: /data, container: /data}
peers: 112
peers_per_host: 16
hostmask: ".*qp-hm.*"
k3_globals:
  role: rows
  master: auto
k3_data:
  - {var: lineitemFiles, path: /local/data/tpch10g/lineitem, policy: global}
  - {var: ordersFiles, path: /local/data/tpch10g/orders, policy: global}
  - {var: customerFiles, path: /local/data/tpch10g/customer, policy: global}
