- hosts: target_hosts
  tasks:
    - include: plays/deploy_k3.yml
      vars:
        app_name: tpch5
        binary: /tmp/tpch5
        log_enabled: false
        numprocs: 16
        k3_variables:
          master: "<192.168.0.40:40000>" # TODO, just set to first peer?
          role: '"rows"'
        data_files:

          - name: "customerFiles"
            num: 1024
            prefix: "/local/data/tpch10g/customer/customer"
          
          - name: "ordersFiles"
            num: 1024
            prefix: "/local/data/tpch10g/orders/orders"

          - name: "lineitemFiles"
            num: 1024
            prefix: "/local/data/tpch10g/lineitem/lineitem"
          
          - name: "supplierFiles"
            num: 1024
            prefix: "/local/data/tpch10g/supplier/supplier"
          
          - name: "nationFiles"
            num: 1
            prefix: "/local/data/tpch10g/nation/nation"

          - name: "regionFiles"
            num: 1
            prefix: "/local/data/tpch10g/region/region"

