- hosts: target_hosts
  tasks:
    - include: plays/deploy_k3.yml
      vars:
        app_name: tpch11
        log_enabled: false
        binary: /tmp/tpch11final
        numprocs: 16
        k3_variables:
          master: "<192.168.0.40:40000>" # TODO, just set to first peer?
          role: '"rows"'
        data_files:
          - name: "partsuppFiles"
            num: 1024
            prefix: "/local/data/tpch10g/partsupp/partsupp"

          - name: "supplierFiles"
            num: 1024
            prefix: "/local/data/tpch10g/supplier/supplier"
          
          - name: "nationFiles"
            num: 1
            prefix: "/local/data/tpch10g/nation/nation"
