- hosts: target_hosts
  tasks:
    - include: ../plays/deploy_k3.yml
      vars:
        app_name: tpch1_normal
        binary: /sigmod/bins/tpch1
        log_enabled: false
        numprocs: 16
        k3_variables:
          master: "<192.168.0.40:40000>" # TODO, just set to first peer?
          role: '"rows"'
        data_files:
          - name: "dataFiles"
            num: 1024
            prefix: "/local/data/tpch1g/lineitem/lineitem"
