name: role 1
peers: 128
hostmask: ".*hm.*"
privileged: True
k3_globals:
  role: [{i: rows}]
  master: auto
  q1_selectivity_date_threshold: 19950618
  q3_selectivity_mktsegments: [{key: AUTOMOBILE, value: []}, {key: BUILDING, value: []}, {key: FURNITURE, value: []}]
  q5_selectivity_regions: [{key: ASIA, value: []}, {key: AMERICA, value: []}, {key: EUROPE, value: []}]
  q6_selectivity_date_lbound: 19920102
  q6_selectivity_date_lbound: 19950618
  q18_selectivity_sum_quantity_threshold: 0
  q22_selectivity_valid_phones: [ {key: "10", value: ()}, {key: "11", value: ()}, {key: "12", value: ()}, {key: "13", value: ()},
                                  {key: "14", value: ()}, {key: "15", value: ()}, {key: "16", value: ()}, {key: "17", value: ()},
                                  {key: "18", value: ()}, {key: "19", value: ()}, {key: "20", value: ()}, {key: "21", value: ()},
                                  {key: "22", value: ()}, {key: "23", value: ()}, {key: "24", value: ()}, {key: "25", value: ()},
                                  {key: "26", value: ()}, {key: "27", value: ()}, {key: "28", value: ()}, {key: "29", value: ()},
                                  {key: "30", value: ()}, {key: "31", value: ()}, {key: "32", value: ()}, {key: "33", value: ()},
                                  {key: "34", value: ()}, {key: "35", value: ()}, {key: "36", value: ()}, {key: "37", value: ()},
                                  {key: "38", value: ()}, {key: "39", value: ()}, {key: "40", value: ()}, {key: "41", value: ()},
                                  {key: "42", value: ()}, {key: "43", value: ()}, {key: "44", value: ()}, {key: "45", value: ()},
                                  {key: "46", value: ()}, {key: "47", value: ()}, {key: "48", value: ()}, {key: "49", value: ()},
                                ]
volumes:
  - {host: /local, container: /local}
k3_data:
  - {var: dataFiles, path: /local/data/tpch10g/lineitem, policy: global}
  - {var: lineitemFiles, path: /local/data/tpch10g/lineitem, policy: global}
  - {var: customerFiles, path: /local/data/tpch10g/customer, policy: global}  
  - {var: ordersFiles, path: /local/data/tpch10g/orders, policy: global}  
  - {var: supplierFiles, path: /local/data/tpch10g/supplier, policy: global}  
  - {var: partsuppFiles, path: /local/data/tpch10g/partsupp, policy: global}  
  - {var: partFiles, path: /local/data/tpch10g/part, policy: global}  
  - {var: regionFiles, path: /local/data/tpch10g/region, policy: replicate}
  - {var: nationFiles, path: /local/data/tpch10g/nation, policy: replicate}
