- hosts: target_hosts
  tasks:
    - include: plays/deploy_k3.yml
      vars:
        app_name: q2
        binary: /tmp/q2
        numprocs: 16
        k3_variables:
          x: "8"
          master: "<192.168.0.41:40000>" # TODO, just set to first peer?
          role: '"rows"'
        data_files:
          - name: "dataFiles"
            num: 512
            prefix: "/local/data/amplab/1024/uservisits/uservisits"
