- hosts: target_hosts
  tasks:
    - include: plays/deploy_k3.yml
      vars:
        app_name: amplab_q4
        binary: /tmp/q4
        numprocs: 1
        k3_variables:
          x: "3"
          master: "<192.168.0.45:40000>" # TODO, just set to first peer?
          role: '"rows"'
        data_files:
          - name: "dataFiles"
            num: 10
            prefix: "/local/data/amplab/1024/crawl/crawl"
